<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Android Debug Bridge</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
<!--            <string>^([\d\- :.]*)(E)\/(.*)\( *(\d+)\): (.*)</string> -->       <!-- adb logcat -v time-->
            <string>^([\d\- :.]*) *(\d+) *(\d+) *(E) ([^:]*): (.*)</string>    <!-- adb logcat -v threadtime-->
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
<!--            <string>^([\d\- :.]*)(F)\/(.*)\( *(\d+)\): (.*)</string> -->       <!-- adb logcat -v time-->
            <string>^([\d\- :.]*) *(\d+) *(\d+) *(F) ([^:]*): (.*)</string>    <!-- adb logcat -v threadtime-->
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>invalid.illegal.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
 <!--           <string>^([\d\- :.]*)(D)\/(.*)\( *(\d+)\): (.*)</string>  -->      <!-- adb logcat -v time-->
            <string>^([\d\- :.]*) *(\d+) *(\d+) *(D) ([^:]*) *: (.*)</string>    <!-- adb logcat -v threadtime-->
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>comment.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
  <!--          <string>^([\d\- :.]*)(I)\/(.*)\( *(\d+)\): (.*)</string>   -->     <!-- adb logcat -v time-->
            <string>^([\d\- :.]*) *(\d+) *(\d+) *(I) ([^:]*) *: (.*)</string>    <!-- adb logcat -v threadtime-->
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>string.adb</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
<!--            <string>^([\d\- :.]*)(W)\/(.*)\( *(\d+)\): (.*)</string>   -->     <!-- adb logcat -v time-->
            <string>^([\d\- :.]*) *(\d+) *(\d+) *(W) ([^:]*): (.*)</string>    <!-- adb logcat -v threadtime-->
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.adb</string>
    <key>uuid</key>
    <string>95F39BAA-EBD3-468A-9965-2C47C3B30C11</string>
</dict>
</plist>
